site_name: Zettlr User Manual
site_url: https://docs.zettlr.com/en
repo_url: https://github.com/Zettlr/zettlr-docs
site_description: >-
    Our comprehensive documentation provides you with everything you need to
    know about how to make the most of Zettlr.
site_author: Hendrik Erz
copyright: "&copy; 2017-2025 by Zettlr"
docs_dir: ../docs/en
site_dir: ../build/en
edit_uri: edit/master/docs/en
extra_css:
  - assets/app.css
nav:
  - Start: index.md
  - Getting Started:
    - Setup: getting-started/setup.md
    - Migrating to a New Computer: getting-started/migrating.md
    - Installing LaTeX: getting-started/installing-latex.md
    - A Note on Security: getting-started/a-note-on-security.md
    - Get involved: getting-started/get-involved.md
    - Troubleshooting: getting-started/troubleshooting.md
    - FAQ: reference/faq.md
  - First Time Users:
    - First Steps: first-time-users/first-steps.md
    - Workspaces: first-time-users/workspaces.md
    - Creating Files and Folders: first-time-users/creating-files-and-folders.md
    - Writing Markdown: first-time-users/writing-markdown.md
    - Migrating from Word: first-time-users/import.md
    - Exporting files: first-time-users/exporting-files.md
  - File Manager:
    - File Manager: file-manager/index.md
    - Workspaces and Root Files: file-manager/workspaces-root-files.md
    - Choosing Which Files To Display: file-manager/choosing-files.md
    - Appearance (Modes): file-manager/appearance.md
    - File List: file-manager/file-list.md
    - Properties: file-manager/properties.md
    - Filtering: file-manager/filtering.md
    - Global Search: file-manager/search.md
    - Projects: file-manager/projects.md
  - Split View:
    - Split View: split-view/index.md
    - Document Tab Bar: split-view/document-tab-bar.md
    - Markdown Editor: split-view/markdown-editor.md
    - Code Editor: split-view/code-editor.md
    - Image Viewer: split-view/image-viewer.md
    - PDF Viewer: split-view/pdf-viewer.md
  - Markdown Editor:
    - Markdown Editor: editor/index.md
    - Markdown Compendium: editor/markdown-compendium.md
    - Appearance: editor/appearance.md
    - Search: editor/search.md
    - Footnotes: editor/footnotes.md
    - Citations: editor/citations.md
    - Working With Comments: core/comments.md
    - Status bar: editor/statusbar.md
    - Table Editor: editor/tables.md
    - Math: core/math.md
    - Code Blocks: core/code-blocks.md
    - Snippets: core/snippets.md
    - YAML Frontmatter: advanced/yaml-frontmatter.md
    - Text Transforms: advanced/text-transforms.md
  - Language and Style:
    - Language and Style: language-style/index.md
    - Spellchecking: language-style/spellchecking.md
    - LanguageTool: language-style/languagetool.md
    - Markdown Syntax: language-style/syntax.md
    - Readability: language-style/readability.md
  - Exporting:
    - Print and Preview: core/print-preview.md
    - Exporting: core/export.md
    - Defaults Files: advanced/defaults-files.md
    - Custom Templates: advanced/custom-templates.md
  - Basic Usage:
    - The User Interface: core/user-interface.md
    - Workspaces and Folders: core/workspaces.md
    - Sidebar: core/sidebar.md
    - AutoCorrect and MagicQuotes: core/autocorrect.md
    - Writing Statistics: core/writing-statistics.md
  - PKMS/Zettelkasten:
    - Zettelkasten Methods: advanced/zkn-method.md
    - Graph View: advanced/graph.md
  - Advanced Usage:
    - Assets Manager: advanced/assets-manager.md
    - Custom CSS: advanced/custom-css.md
    - Tag Manager: advanced/tag-manager.md
    - Pomodoro Timer: advanced/pomodoro.md
  - Guides:
    - Zotero Integration: guides/reference-manager-integration.md
    - LanguageTool Locally: guides/languagetool-local.md
    - Presentations: guides/presentations.md
    - Submitting to a Journal using a LaTeX Template: guides/journal-latex-template.md
    - Portable App: guides/portable.md
  - References:
    - Keyboard Shortcuts: reference/keyboard-shortcuts.md
    - Markdown Basics: reference/markdown-basics.md
    - Settings: reference/settings.md
theme:
  name: readthedocs
  locale: en
  custom_dir: ../theme_override
  highlightjs: True
  prev_next_buttons_location: both
  hljs_languages:
    - javascript
    - markdown
    - css
    - yaml
    - latex
markdown_extensions:
    - def_list
    - admonition
    - toc:
        permalink: True
plugins:
  - search:
      lang: en
validation:
  omitted_files: warn
  absolute_links: warn  # Or 'relative_to_docs' - new in MkDocs 1.6
  unrecognized_links: warn
  anchors: warn  # New in MkDocs 1.6
