site_name: Zettlr Docs
site_url: https://docs.zettlr.com/fr
repo_url: https://github.com/Zettlr/zettlr-docs
site_description: >-
    Notre documentation complète vous fournit tout ce que vous devez savoir
    pour tirer le meilleur parti de Zettlr.
site_author: Hendrik Erz
copyright: "&copy; 2017-2020 by Zettlr"
docs_dir: ../docs/fr
site_dir: ../build/fr
edit_uri: edit/master/docs/fr
extra_css:
  - assets/app.css
nav:
  - Accueil: index.md
  - Installation: install.md
  - Zettlr en 5 minutes: 5-minutes.md
  - Guides:
    - Zettlr comme application de prise de notes: guides/guide-notes.md
    - Zettlr comme Zettelkasten: guides/guide-zettelkasten.md
    - Zettlr comme environnement de développement intégré (IDE): guides/guide-ide.md
  - Fonctionnalités de base:
    - L'éditeur: core/editor.md
    - La liste de fichiers: core/file-list.md
    - Rechercher: core/search.md
    - Exporter avec Zettlr: core/export.md
    - Les tableaux dans Zettlr: core/tables.md
    - CSS personnalisée: core/custom-css.md
    - Localisation linguistique: core/localisation.md
    - Le panneau des annexes: core/attachments.md
  - Outils académiques:
    - Citations: academic/citations.md
    - Projets: academic/projects.md
    - Présentations: academic/presentations.md
    - Minuteur Pomodoro: academic/pomodoro.md
    - Lisibilité: academic/readability.md
    - Méthode Zettelkasten: academic/zkn-method.md
    - Modèles personnalisés: academic/custom-templates.md
  - Références:
    - Raccourcis: reference/shortcuts.md
    - Les bases de Markdown: reference/markdown-basics.md
    - Paramétrage: reference/settings.md
    - Dictionnaires et vérification orthographique: reference/spell-checking.md
  - Impliquez-vous: get-involved.md
  - FAQ: faq.md
theme:
  name: readthedocs
  custom_dir: ../theme_override
  highlightjs: True
  prev_next_buttons_location: both
  hljs_languages:
    - javascript
    - css
    - yaml
    - tex
markdown_extensions:
    - toc:
        permalink: True
plugins:
  - search:
      lang: fr
